- type: entity
  parent:
  - CE14ClothingCloakBase
  - CE14ClothingBaseContainer
  id: CE14ClothingCloakBlacksmithArpon
  name: blacksmith's apron
  description: Loose leather strips, still actually being clothing.
  components:
  - type: Sprite
    sprite: _CE14/Clothing/Cloak/Roles/General/blacksmith_apron.rsi
  - type: Clothing
    sprite: _CE14/Clothing/Cloak/Roles/General/blacksmith_apron.rsi
  - type: Armor
    modifiers:
      coefficients:
        Heat: 0.95
  - type: Butcherable
    butcheringType: Knife
    spawned:
    - id: CE14RuggedLeather1
      amount: 1
  - type: Storage
    maxItemSize: Small
    defaultStorageOrientation: Vertical
    grid:
    - 0,0,2,1
    whitelist:
      tags:
        - Crayon
        - CE14Lighter
        - CE14Scissors
        - CE14SharpeningStone
