- type: CE14VampireFaction
  id: Unnameable
  name: CE14-vampire-fraction-name-unnameable
  factionIcon: CE14VampireUnnameable
  singletonTeleportKey: CE14VampirePortalGlyphUnnameable

- type: CE14VampireFaction
  id: Devourers
  name: CE14-vampire-fraction-name-devourers
  factionIcon: CE14VampireDevourers
  singletonTeleportKey: CE14VampirePortalGlyphDevourers

- type: CE14VampireFaction
  id: NightChildrens
  name: CE14-vampire-fraction-name-night-childrens
  factionIcon: CE14VampireNightChildrens
  singletonTeleportKey: CE14VampirePortalGlyphNightChildrens