- type: job
  id: CE14Merchant
  setPreference: true
  name: CE14-job-name-merchant
  description: CE14-job-desc-merchant
  playTimeTracker: CE14JobMerchant
  startingGear: CE14MerchantGear
  icon: "CE14JobIconMerchant"
  supervisors: CE14-job-supervisors-commandant
  canBeAntag: false
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 3600 # 1 hours
  special:
    - !type:CE14AddTradingReputationSpecial
      factions:
      - VictoriaGardens
      - BradPotions
      - DwarfMining
      - Thaumaturgy
      - HomeDecor
      - Horticulture
      - Butchers
      - Dairy
      - Tailors
      - HelmirChild
    - !type:CE14LearnSkillsSpecial
      skills:
      - TraderWit

- type: startingGear
  id: CE14MerchantGear
  storage:
    back:
    - CE14EnergyCrystalMedium
    - CE14EnergyCrystalMedium
  equipment:
    belt: CE14WalletFilledTest
    keys: CE14KeyRingMerchant

