- type: job
  id: CE14GodLumera
  name: CE14-job-name-god-lumera
  description: CE14-job-desc-god-lumera
  setPreference: false
  playTimeTracker: CE14GodLumera
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hrs
  canBeAntag: false
  icon: CE14JobIconGodLumera
  jobEntity: CE14MobGodLumera
  joinNotifyCrew: false
  requireAdminNotify: true
  jobPreviewEntity: CE14MobGodLumera
  applyTraits: false