- type: job
  id: CE14GodMerkas
  name: CE14-job-name-god-merkas
  description: CE14-job-desc-god-merkas
  setPreference: false
  playTimeTracker: CE14GodMerkas
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hrs
  canBeAntag: false
  icon: CE14JobIconGodMerkas
  jobEntity: CE14MobGodMerkas
  joinNotifyCrew: false
  requireAdminNotify: true
  jobPreviewEntity: CE14MobGodMerkas
  applyTraits: false