
# Artisans

- type: playTimeTracker
  id: CE14JobApprentice

- type: playTimeTracker
  id: CE14JobAlchemist

- type: playTimeTracker
  id: CE14JobBlacksmith

- type: playTimeTracker
  id: CE14JobInnkeeper

# Mercenary

- type: playTimeTracker
  id: CE14JobGuildmaster

- type: playTimeTracker
  id: CE14JobGuildWorker

- type: playTimeTracker
  id: CE14JobAdventurer

# Guard

- type: playTimeTracker
  id: CE14JobGuardCommander

- type: playTimeTracker
  id: CE14JobGuard

- type: playTimeTracker
  id: CE14JobInvestigator

# Trade guild

- type: playTimeTracker
  id: CE14JobCommandant

- type: playTimeTracker
  id: CE14JobMerchant

# Gods
- type: playTimeTracker
  id: CE14GodMerkas

- type: playTimeTracker
  id: CE14GodLumera