- type: department
  id: CE14Demigods
  name: department-CE14Demigods
  description: department-CE14Demigods-desc
  weight: 666 # >:)
  color: "#ffffff"
  editorHidden: true
  roles:
  - CE14GodLumera
  - CE14GodMerkas

- type: department
  id: CE14Command
  name: department-CE14Command
  description: department-CE14Command-desc
  primary: false
  weight: 10
  color: "#3ec8fa"
  editorHidden: true
  roles:
  - CE14GuardCommander
  - CE14Guildmaster

- type: department
  id: CE14Guard
  name: department-CE14Guard
  description: department-CE14Guard-desc
  weight: 9
  color: "#576384"
  editorHidden: false
  roles:
  - CE14GuardCommander
  - CE14Investigator
  - CE14Guard

- type: department
  id: CE14Artisan
  name: department-CE14Artisan
  description: department-CE14Artisan-desc
  weight: 7
  color: "#834833"
  roles:
  - CE14Merchant
  - CE14Alchemist
  - CE14Blacksmith
  - CE14Apprentice
  - CE14Innkeeper

- type: department
  id: CE14Mercenary
  name: department-CE14Mercenary
  description: department-CE14Mercenary-desc
  weight: 6
  color: "#588151"
  roles:
  - CE14Guildmaster
  - CE14GuildWorker
  - CE14Adventurer