using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE14.UserInterface.Systems.Skill.Window;

[GenerateTypedNameReferences]
public sealed partial class CE14SkillWindow : DefaultWindow
{
    public CE14SkillWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
