- type: entity
  parent: CE14ClothingPantsBase
  id: CE14ClothingPantsAristocratic
  name: aristocrat's pants
  description: Pants with enough quality fabric that you don't want to cave in them.
  components:
  - type: Sprite
    sprite: _CE14/Clothing/Pants/aristocratic.rsi
  - type: Clothing
    sprite: _CE14/Clothing/Pants/aristocratic.rsi

- type: entity
  parent: CE14ClothingPantsBase
  id: CE14ClothingPantsMerchantsPantaloons
  name: merchant's pantaloons
  components:
  - type: Sprite
    sprite: _CE14/Clothing/Pants/merchants_pantaloons.rsi
  - type: Clothing
    sprite: _CE14/Clothing/Pants/merchants_pantaloons.rsi

