- type: entity
  parent: CE14ClothingShirtBase
  id: CE14ClothingShirtMerchant
  name: merchant's shirt
  description: A white shirt with bronze inserts.
  components:
  - type: Sprite
    sprite: _CE14/Clothing/Shirt/Roles/Merchant/merchant.rsi
  - type: Clothing
    sprite: _CE14/Clothing/Shirt/Roles/Merchant/merchant.rsi

- type: entity
  parent: CE14ClothingShirtBase
  id: CE14ClothingShirtMerchantDress
  name: merchant's dress
  description: An elegant dress for equally elegant individuals.
  components:
  - type: Sprite
    sprite: _CE14/Clothing/Shirt/Roles/Merchant/merchants_dress.rsi
  - type: Clothing
    sprite: _CE14/Clothing/Shirt/Roles/Merchant/merchants_dress.rsi

