- type: Tag
  id: CE14RecipeSewing

- type: Tag
  id: CE14RecipeCooking

- type: Tag
  id: CE14RecipeWorkbench

- type: Tag
  id: CE14RecipeAnvil

- type: Tag
  id: CE14RecipeMeltingFurnace

- type: Tag
  id: CE14RecipeLeatherWorking

- type: Tag
  id: CE14RecipeVampire
  