- type: job
  id: CE14Adventurer
  name: CE14-job-name-adventurer
  description: CE14-job-desc-adventurer
  playTimeTracker: CE14JobAdventurer
  startingGear: CE14AdventurerGear
  icon: "CE14JobIconAdventurer"
  supervisors: CE14-job-supervisors-guildmaster

- type: startingGear
  id: CE14AdventurerGear
  storage:
    back:
    - CE14EnergyCrystalMedium
    - CE14EnergyCrystalMedium
  equipment:
    keys: CE14BaseKeyRing
    belt: CE14WalletFilledTest
