- type: job
  id: CE14GuildWorker
  name: CE14-job-name-guildworker
  description: CE14-job-desc-guildworker
  playTimeTracker: CE14JobGuildWorker
  startingGear: CE14GuildWorkerGear
  icon: "CE14JobIconGuildWorker"
  supervisors: CE14-job-supervisors-guildmaster
  weight: 2
  requirements:
    - !type:RoleTimeRequirement
      role: CE14JobAdventurer
      time: 7200 # 2 hours
  special:
    - !type:AddComponentSpecial
      components:
      - type: CE14SalaryCounter
        salary: 50

- type: startingGear
  id: CE14GuildWorkerGear
  storage:
    back:
    - CE14EnergyCrystalMedium
    - CE14EnergyCrystalMedium
  equipment:
    keys: CE14KeyRingGuildworker
    belt: CE14WalletFilledTest
