- type: job
  id: CE14Guildmaster
  setPreference: true
  name: CE14-job-name-guildmaster
  description: CE14-job-desc-guildmaster
  playTimeTracker: CE14JobGuildmaster
  startingGear: CE14GuildmasterGear
  icon: "CE14JobIconGuildmaster"
  requireAdminNotify: true
  joinNotifyCrew: true
  canBeAntag: false
  supervisors: CE14-job-supervisors-command
  weight: 3
  requirements:
    #- !type:RoleTimeRequirement
    #  role: CE14JobGuildWorker
    #  time: 7200 # 2 hours
    - !type:RoleTimeRequirement
      role: CE14JobAdventurer
      time: 18000 # 5 hours
  special:
    - !type:AddComponentSpecial
      components:
      - type: CE14SalaryCounter
        salary: 200

- type: startingGear
  id: CE14GuildmasterGear
  storage:
    back:
    - CE14EnergyCrystalMedium
  equipment:
    belt: CE14WalletFilledTest
    keys: CE14KeyRingGuildmaster