- type: entity
  parent: CE14ClothingHeadBase
  id: CE14ClothingHeadWreath
  name: floral wreath
  description: A simple flower decoration. That's so sweet.
  components:
  - type: Sprite
    sprite: _CE14/Clothing/Head/Produced/wreath.rsi
  - type: Clothing
    sprite: _CE14/Clothing/Head/Produced/wreath.rsi
  #- type: Construction
  #  graph: CE14HeadWreath
  #  node: CE14headwreath
