using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CE14.Options;

[GenerateTypedNameReferences]
public sealed partial class CE14OptionsMenuMainTab : Control
{
    public CE14OptionsMenuMainTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(CCVars.WaveShaderEnabled, WaveShaderEnabled);
        Control.AddOptionCheckBox(CCVars.PostProcess, PostProcessCheckBox);

        Control.Initialize();
    }
}
