- type: job
  id: CE14Guard
  setPreference: true
  name: CE14-job-name-guard
  description: CE14-job-desc-guard
  playTimeTracker: CE14JobGuard
  startingGear: CE14GuardGear
  icon: "CE14JobIconGuard"
  supervisors: CE14-job-supervisors-guard-commander
  canBeAntag: false
  special:
    #- !type:CE14LearnSkillsSpecial
    #  skills:
    #  - SwordMastery
    - !type:AddComponentSpecial
      components:
      - type: CE14SalaryCounter
        salary: 50
    - !type:CE14AddTradingReputationSpecial
      factions:
      - Guards

- type: startingGear
  id: CE14GuardGear
  equipment:
    keys: CE14KeyRingGuard
    belt: CE14WalletFilledTest

