- type: job
  id: CE14Investigator
  setPreference: true
  name: CE14-job-name-investigator
  description: CE14-job-desc-investigator
  playTimeTracker: CE14JobInvestigator
  startingGear: CE14InvestigatorGear
  icon: "CE14JobIconInvestigator"
  supervisors: CE14-job-supervisors-guard-commander
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: CE14Guard
      time: 3600 # 1 hours
  special:
    - !type:CE14LearnSkillsSpecial
      skills:
      - CE14ActionSpellMagicSplitting
      - CE14ActionToggleMagicVision
    - !type:AddComponentSpecial
      components:
      - type: CE14SalaryCounter
        salary: 75
    - !type:CE14AddTradingReputationSpecial
      factions:
      - Guards
      - Thaumaturgy

- type: startingGear
  id: CE14InvestigatorGear
  equipment:
    keys: CE14KeyRingGuard
    belt: CE14WalletFilledTest

