- type: startingGear
  id: CE14DeathMatchGear
  equipment:
    cloak: CE14ClothingCloakFurcapeBlue
    shirt: CE14ClothingShirtCottonBlack
    pants: CE14ClothingPantsLoincloth
    shoes: CE14ClothingShoesSandals

