- type: entity
  id: CE14BaseRoof
  categories: [ ForkFiltered ]
  abstract: true
  name: roof
  description: A roof over your head to protect you from the heat of the sun or the weather.
  placement:
    mode: SnapgridCenter
  components:
  - type: PlacementReplacement
    key: CE14Roof
  - type: Physics
    bodyType: Static
    canCollide: false
  - type: Transform
    anchored: true
  - type: BlockWeather
  - type: CE14Roof
  - type: Sprite
    drawdepth: Effects
    sprite: _CE14/Structures/Roof/test.rsi
  - type: Icon
    sprite: _CE14/Structures/Roof/test.rsi
    state: full
  - type: IconSmooth
    key: CE14roof
    base: roof
  - type: IsRoof
  - type: SunShadowCast
  - type: WallMount
    arc: 360

- type: entity
  parent:
  - CE14BaseRoof
  - CE14BaseFlammableSpreading
  id: CE14RoofWooden
  name: wooden roof
  components:
  - type: Sprite
    sprite: _CE14/Structures/Roof/wooden.rsi
  - type: Icon
    sprite: _CE14/Structures/Roof/wooden.rsi
  - type: Damageable
    damageContainer: Inorganic
    damageModifierSet: Wood
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 100
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: WoodDestroy
      - !type:SpawnEntitiesBehavior
        spawn:
          CE14WoodenPlanks1:
            min: 1
            max: 1
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Construction
    graph: CE14RoofWooden
    node: CE14RoofWooden

- type: entity
  id: CE14RoofWoodenBirch
  parent: CE14RoofWooden
  components:
  - type: Sprite
    sprite: _CE14/Structures/Roof/birch.rsi
  - type: Icon
    sprite: _CE14/Structures/Roof/birch.rsi
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 100
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: WoodDestroy
      - !type:SpawnEntitiesBehavior
        spawn:
          CE14BirchWoodenPlanks1:
            min: 1
            max: 1
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Construction
    graph: CE14RoofWooden
    node: CE14RoofWoodenBirch

- type: entity
  parent:
  - CE14BaseRoof
  id: CE14RoofStone
  name: stone roof
  components:
  - type: Sprite
    sprite: _CE14/Structures/Roof/stone.rsi
  - type: Icon
    sprite: _CE14/Structures/Roof/stone.rsi
  - type: Damageable
    damageContainer: StructuralInorganic
    damageModifierSet: Rock
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 150
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          path: /Audio/Effects/break_stone.ogg
          params:
            volume: -6
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Construction
    graph: CE14RoofStone
    node: CE14RoofStone

- type: entity
  parent:
  - CE14BaseRoof
  id: CE14RoofRemover
  name: roof remover debug
  components:
  - type: Sprite
    sprite: _CE14/Structures/Roof/stone.rsi
  - type: Icon
    sprite: _CE14/Structures/Roof/stone.rsi
  - type: TimedDespawn
    lifetime: 2
