- type: tile
  editorHidden: false
  id: CE14FloorFoundation
  name: CE14-tiles-foundation
  sprite: /Textures/_CE14/Tiles/foundation.png
  variants: 14
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 99 #Dont have edges, but block natural ones
  baseTurf: CE14FloorBase
  isSubfloor: true
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: CE14FloorTileFoundation

- type: tile
  editorHidden: false
  id: CE14FloorStonebricks
  name: CE14-tiles-stonebricks
  sprite: /Textures/_CE14/Tiles/Stonebricks/stonebricks.png
  variants: 9
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_CE14/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_CE14/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_CE14/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_CE14/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_CE14/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_CE14/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_CE14/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_CE14/Tiles/Stonebricks/double_edge_W.png
  baseTurf: CE14FloorFoundation
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: CE14FloorTileStonebricks

- type: tile
  editorHidden: false
  id: CE14FloorStonebricksSnowed
  name: CE14-tiles-stonebricks
  sprite: /Textures/_CE14/Tiles/Stonebricks/snowstonebricks.png
  variants: 9
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_CE14/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_CE14/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_CE14/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_CE14/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_CE14/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_CE14/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_CE14/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_CE14/Tiles/Stonebricks/double_edge_W.png
  baseTurf: CE14FloorFoundation
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: CE14FloorTileStonebricks

- type: tile
  editorHidden: false
  id: CE14FloorStonebricksSmallCarved1
  name: CE14-tiles-stonebricks-small-carved1
  sprite: /Textures/_CE14/Tiles/Stonebricks/stonebricks_small_carved_1.png
  variants: 1
  placementVariants:
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_CE14/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_CE14/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_CE14/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_CE14/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_CE14/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_CE14/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_CE14/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_CE14/Tiles/Stonebricks/double_edge_W.png
  baseTurf: CE14FloorFoundation
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: CE14FloorTileStonebricksSmallCarved

- type: tile
  editorHidden: false
  id: CE14FloorStonebricksSmallCarved2
  name: CE14-tiles-stonebricks-small-carved2
  sprite: /Textures/_CE14/Tiles/Stonebricks/stonebricks_small_carved_2.png
  variants: 1
  placementVariants:
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_CE14/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_CE14/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_CE14/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_CE14/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_CE14/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_CE14/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_CE14/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_CE14/Tiles/Stonebricks/double_edge_W.png
  baseTurf: CE14FloorFoundation
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: CE14FloorTileStonebricksSmallCarved2

- type: tile
  editorHidden: false
  id: CE14FloorStonebricksSquareCarved
  name: CE14-tiles-stonebricks-square-carved
  sprite: /Textures/_CE14/Tiles/Stonebricks/stonebricks_square_carved.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_CE14/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_CE14/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_CE14/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_CE14/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_CE14/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_CE14/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_CE14/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_CE14/Tiles/Stonebricks/double_edge_W.png
  baseTurf: CE14FloorFoundation
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: CE14FloorTileStonebricksSquareCarved

- type: tile
  editorHidden: false
  id: CE14FloorMarble
  name: CE14-tiles-stonebricks-marble
  sprite: /Textures/_CE14/Tiles/Marble/marble.png
  variants: 6
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 102
  edgeSprites:
    South: /Textures/_CE14/Tiles/Marble/double_edge_S.png
  baseTurf: CE14FloorFoundation
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: CE14FloorTileMarbleBrick

- type: tile
  editorHidden: false
  id: CE14FloorMarbleSmallbricks
  name: CE14-tiles-stonebricks-marble
  sprite: /Textures/_CE14/Tiles/Marble/small_bricks.png
  variants: 9
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 102
  edgeSprites:
    South: /Textures/_CE14/Tiles/Marble/double_edge_S.png
  baseTurf: CE14FloorFoundation
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: CE14FloorTileMarbleSmallbricks

- type: tile
  editorHidden: false
  id: CE14FloorDirtSeedbed
  name: CE14-tiles-dirt-seedbed
  sprite: /Textures/_CE14/Tiles/DirtSeedBag/seedbed.png
  variants: 2
  placementVariants:
  - 1.0
  - 1.0
  edgeSpritePriority: 100
  edgeSprites:
    SouthEast: /Textures/_CE14/Tiles/DirtSeedBag/single_edge_SE.png
    NorthEast: /Textures/_CE14/Tiles/DirtSeedBag/single_edge_NE.png
    NorthWest: /Textures/_CE14/Tiles/DirtSeedBag/single_edge_NW.png
    SouthWest: /Textures/_CE14/Tiles/DirtSeedBag/single_edge_SW.png
    South: /Textures/_CE14/Tiles/DirtSeedBag/double_edge_S.png
    East: /Textures/_CE14/Tiles/DirtSeedBag/double_edge_E.png
    North: /Textures/_CE14/Tiles/DirtSeedBag/double_edge_N.png
    West: /Textures/_CE14/Tiles/DirtSeedBag/double_edge_W.png
  baseTurf: CE14FloorDirt
  deconstructTools: [ CE14Digging ]
  itemDrop: CE14DirtEffect
  isSubfloor: true
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true

