- type: entity
  parent: CE14ClothingHeadBase
  id: CE14ClothingHeadAlchemistBandana
  name: alchemist's bandana
  description: Hides your hair from chemical fumes
  components:
  - type: Sprite
    sprite: _CE14/Clothing/Head/Roles/Alchemist/bandana.rsi
  - type: Clothing
    sprite: _CE14/Clothing/Head/Roles/Alchemist/bandana.rsi

- type: entity
  parent: CE14ClothingHeadBase
  id: CE14ClothingHeadAlchemistBeret
  name: alchemist's beret
  description: You seem very smart.
  components:
  - type: Sprite
    sprite: _CE14/Clothing/Head/Roles/Alchemist/beret.rsi
  - type: Clothing
    sprite: _CE14/Clothing/Head/Roles/Alchemist/beret.rsi

