- type: entity
  parent: CE14ClothingHeadBase
  id: CE14ClothingHeadGildmaster
  name: guildmaster hat
  description: A sign of unlimited experience and honor.
  components:
  - type: Sprite
    sprite: _CE14/Clothing/Head/Roles/Guildmaster/guildmaster_hat.rsi
  - type: Clothing
    sprite: _CE14/Clothing/Head/Roles/Guildmaster/guildmaster_hat.rsi

