- type: entity
  parent: CE14ClothingHeadBase
  id: CE14ClothingHeadBowler
  name: bowler hat
  description: It has an aristocratic vibe about it...
  components:
  - type: Sprite
    sprite: _CE14/Clothing/Head/Roles/Merchant/bowler_hat.rsi
  - type: Clothing
    sprite: _CE14/Clothing/Head/Roles/Merchant/bowler_hat.rsi

- type: entity
  parent: CE14ClothingHeadBase
  id: CE14ClothingHeadBowlerGolden
  name: golden bowler hat
  description: What an exquisite hat. It's clearly a hat that only sophisticated people prefer to wear.
  components:
  - type: Sprite
    sprite: _CE14/Clothing/Head/Roles/Merchant/bowler_golden_hat.rsi
  - type: Clothing
    sprite: _CE14/Clothing/Head/Roles/Merchant/bowler_golden_hat.rsi

