using System.Linq;
using System.Numerics;
using Content.Client._CE14.UserInterface;
using Content.Client._CE14.UserInterface.Systems.NodeTree;
using Content.Shared._CE14.Trading;
using Content.Shared._CE14.Trading.Components;
using Content.Shared._CE14.Trading.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Audio.Systems;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._CE14.Trading;

[GenerateTypedNameReferences]
public sealed partial class CE14TradingPlatformWindow : DefaultWindow
{
    [Dependency] private readonly ILogManager _log = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntityManager _e = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly CE14ClientTradingPlatformSystem _tradingSystem;
    private readonly CE14ClientStationEconomySystem _economySystem;

    private CE14TradingPlatformUiState? _cacheState;
    private Entity<CE14TradingReputationComponent>? _cachedUser;
    private Entity<CE14TradingPlatformComponent>? _cachedPlatform;

    private IEnumerable<CE14TradingPositionPrototype> _allPositions = [];

    private ProtoId<CE14TradingFactionPrototype>? _selectedFaction;
    private CE14TradingPositionPrototype? _selectedPosition;
    public event Action<ProtoId<CE14TradingPositionPrototype>>? OnBuy;

    private ISawmill Sawmill { get; init; }

    public CE14TradingPlatformWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Sawmill = _log.GetSawmill("CE14_trading");

        CacheSkillProto();
        _proto.PrototypesReloaded += _ => CacheSkillProto();
        if (_cachedUser is not null)
        {
            foreach (var (f, _) in _cachedUser.Value.Comp.Reputation)
            {
                if (_proto.TryIndex(f, out var indexedFaction))
                {
                    SelectFaction(indexedFaction);
                    break;
                }
            }
        }

        _tradingSystem = _e.System<CE14ClientTradingPlatformSystem>();
        _economySystem = _e.System<CE14ClientStationEconomySystem>();

        GraphControl.OnOffsetChanged += offset =>
        {
            ParallaxBackground.Offset = -offset * 0.25f + new Vector2(1000, 1000); //hardcoding is bad
        };
        GraphControl.OnNodeSelected += SelectNode;
        BuyButton.OnPressed += BuyPressed;
    }

    private void BuyPressed(BaseButton.ButtonEventArgs obj)
    {
        if (_selectedPosition is null)
            return;

        OnBuy?.Invoke(_selectedPosition.ID);
    }

    private void SelectNode(CE14NodeTreeElement? node)
    {
        if (node == null)
        {
            DeselectNode();
            return;
        }

        if (_cacheState == null)
        {
            Sawmill.Error("Tried to select node without a cached state.");
            return;
        }

        if (!_proto.TryIndex<CE14TradingPositionPrototype>(node.NodeKey, out var indexedPosition))
            return;

        SelectNode(indexedPosition);
    }

    private void SelectNode(CE14TradingPositionPrototype? node)
    {
        if (node is null || _cachedUser is null || _cachedPlatform is null)
        {
            DeselectNode();
            return;
        }

        if (_cacheState == null)
        {
            Sawmill.Error("Tried to select node without a cached state.");
            return;
        }

        _selectedPosition = node;
        var unlocked = _cachedUser.Value.Comp.Reputation[_selectedPosition.Faction] >= _selectedPosition.ReputationLevel;

        Name.Text = _tradingSystem.GetTradeName(_selectedPosition);
        Description.Text = _tradingSystem.GetTradeDescription(_selectedPosition);

        LocationView.Texture = _selectedPosition.Icon.Frame0();
        BuyButton.Disabled = !unlocked;

        UnlockCost.Text = _selectedPosition.ReputationLevel.ToString();

        BuyPriceHolder.RemoveAllChildren();
        var price = _economySystem.GetPrice(_selectedPosition) * _cachedPlatform.Value.Comp.PlatformMarkupProcent ?? 0;
        BuyPriceHolder.AddChild(new CE14PriceControl((int)price));
    }

    private void DeselectNode()
    {
        Name.Text = string.Empty;
        Description.Text = string.Empty;
        LocationView.Texture = null;
    }

    private void CacheSkillProto()
    {
        _allPositions = _proto.EnumeratePrototypes<CE14TradingPositionPrototype>();
        UpdateGraphControl();
    }

    public void UpdateState(CE14TradingPlatformUiState state)
    {
        _cacheState = state;

        if (!_e.TryGetComponent<CE14TradingReputationComponent>(_player.LocalEntity, out var repComp))
            return;

        _cachedUser = (_player.LocalEntity.Value, repComp);

        var plat = _e.GetEntity(state.Platform);
        if (!_e.TryGetComponent<CE14TradingPlatformComponent>(plat, out var platComp))
            return;

        _cachedPlatform = (plat, platComp);
        UpdateGraphControl();
    }

    private void UpdateGraphControl()
    {
        if (_cachedUser is null)
            return;

        HashSet<CE14NodeTreeElement> nodeTreeElements = new();
        var edges = new HashSet<(string, string)>();
        foreach (var position in _allPositions)
        {
            if (position.Faction != _selectedFaction)
                continue;

            var unlocked = _cachedUser.Value.Comp.Reputation[position.Faction] >= position.ReputationLevel;
            var active = _tradingSystem.CanBuyPosition((_cachedUser.Value.Owner, _cachedUser.Value.Comp), position);
            var node = new CE14NodeTreeElement(position.ID, unlocked, active, new Vector2(position.ReputationLevel.Float() * 50, position.UiPosition * 50) , position.Icon);
            nodeTreeElements.Add(node);
        }

        GraphControl.UpdateState(
            new CE14NodeTreeUiState(
                nodeTreeElements,
                edges: edges,
                frameIcon: new SpriteSpecifier.Rsi(
                    new ResPath("/Textures/_CE14/Interface/NodeTree/trading.rsi"),
                    "frame"),
                hoveredIcon: new SpriteSpecifier.Rsi(
                    new ResPath("/Textures/_CE14/Interface/NodeTree/trading.rsi"),
                    "hovered"),
                selectedIcon: new SpriteSpecifier.Rsi(
                    new ResPath("/Textures/_CE14/Interface/NodeTree/trading.rsi"),
                    "selected"),
                learnedIcon: new SpriteSpecifier.Rsi(
                    new ResPath("/Textures/_CE14/Interface/NodeTree/trading.rsi"),
                    "learned"),
                activeLineColor: new Color(172, 102, 190),
                lineColor: new Color(83, 40, 121)
            )
        );

        //Faction tabs update
        TreeTabsContainer.RemoveAllChildren();
        foreach (var (faction, rep) in _cachedUser.Value.Comp.Reputation)
        {
            if (!_proto.TryIndex(faction, out var indexedFaction))
                continue;
            var factionButton = new CE14TradingFactionButtonControl(
                indexedFaction.Color,
                Loc.GetString(indexedFaction.Name),
                rep);

            factionButton.OnPressed += () =>
            {
                SelectFaction(indexedFaction);
            };

            TreeTabsContainer.AddChild(factionButton);
        }
        SelectNode(_selectedPosition);
    }

    private void SelectFaction(CE14TradingFactionPrototype faction)
    {
        _selectedFaction = faction;
        TreeName.Text = Loc.GetString("CE14-trading-faction-prefix") + " " + Loc.GetString(faction.Name);
        UpdateGraphControl();
    }
}
