- type: entity
  parent: BaseMindRoleAntag
  id: CE14MindRoleDemiplaneAntag
  name: Demiplane antag role
  components:
  - type: MindRole
    roleType: CE14DemiplaneAntagonist
    antagPrototype: CE14DemiplaneAntag

- type: entity
  parent: BaseMindRoleAntag
  id: CE14MindRoleVampire
  categories: [ ForkFiltered ]
  name: Vampire role
  components:
  - type: MindRole
    antagPrototype: CE14Vampire
    roleType: TeamAntagonist
    exclusiveAntag: true
  - type: CE14VampireRole

- type: entity
  parent: BaseMindRoleAntag
  id: CE14MindRoleBloodMoonCursed
  categories: [ ForkFiltered ]
  name: Blood moon cursed role
  components:
  - type: MindRole
    antagPrototype: CE14BloodMoonCursed
    roleType: SoloAntagonist
    exclusiveAntag: false

