- type: entity
  abstract: true
  id: CE14BurnsAsh
  categories: [ ForkFiltered ]
  components:
  - type: Temperature
    currentTemperature: 290
  - type: InternalTemperature
    thickness: 0.02
    area: 0.02
  - type: CE14TemperatureTransformation
    entries:
    - temperatureRange: 400, 500
      transformTo: CE14Ash1
