- type: entity
  id: CE14BaseExpedition
  categories: [ HideSpawnMenu ]
  parent:
  - BaseStation
  - BaseStationAllEventsEligible
  - BaseStationJobsSpawning
  - BaseStationAlertLevels
  - BaseStationRecords # Required for lobby manifest + cryo leave
  - CE14BaseStationCommonObjectives
  - CE14BaseStationEconomy
  - CE14BaseStationDemiplanes
  #- CE14BaseStationGods

- type: entity
  id: CE14BaseStationCommonObjectives
  abstract: true
  components:
    - type: CE14StationCommonObjectives

- type: entity
  id: CE14BaseStationEconomy
  abstract: true
  components:
    - type: CE14StationEconomy

- type: entity
  id: CE14BaseStationDemiplanes
  abstract: true
  components:
    - type: CE14StationDemiplaneMap

#- type: entity
#  id: CE14BaseStationGods
#  abstract: true
#  components:
#    - type: CE14StationRandomJobs
#      entries:
#      - jobs:
#        - CE14GodMerkas
#        - CE14GodLumera
#        count:
#          min: 2
#          max: 2