- type: job
  id: CE14Apprentice
  name: CE14-job-name-apprentice
  description: CE14-job-desc-apprentice
  playTimeTracker: CE14JobApprentice
  startingGear: CE14ApprenticeGear
  icon: "CE14JobIconApprentice"
  supervisors: CE14-job-supervisors-command
  special:
    - !type:CE14AddTradingReputationSpecial
      factions:
      - DwarfMining
      - HomeDecor
      - Tailors
      - Horticulture
      - Butchers
      - Dairy
    - !type:CE14LearnSkillsSpecial
      skills:
      #- CopperMelting
      - AlchemyVision

- type: startingGear
  id: CE14ApprenticeGear
  storage:
    back:
    - CE14EnergyCrystalMedium
    - CE14EnergyCrystalMedium
  equipment:
    keys: CE14BaseKeyRing
    belt: CE14WalletFilledTest
