- type: job
  id: CE14Innkeeper
  name: CE14-job-name-innkeeper
  description: CE14-job-desc-innkeeper
  playTimeTracker: CE14JobInnkeeper
  startingGear: CE14InnkeeperGear
  icon: "CE14JobIconInnkeeper"
  supervisors: CE14-job-supervisors-command
  special:
    - !type:CE14AddTradingReputationSpecial
      factions:
      - VictoriaGardens
      - HomeDecor
      - Butchers
      - Dairy
    - !type:CE14LearnSkillsSpecial
      skills:
      - TraderWit # Craftsmen have always taken this perk. The main purpose of craftsmen is trade.

- type: startingGear
  id: CE14InnkeeperGear
  storage:
    back:
    - CE14EnergyCrystalMedium
  equipment:
    belt: CE14WalletFilledTest
    keys: CE14KeyRingInnkeeper
